## ECBM E4040 Neural Networks and Deep Learning 
### Columbia University, Fall 2022.

# ECBM E4040 - Assignment 0 

The assignment is distributed as a Jupyter notebook called Assignment 0.ipynb from a Github repository (or as a zip file).  Additional instructions and support material for the assignment can be found in file README.md which comes with the assignment and in a set of webpages under https://ecbme4040.github.io. The assignment uses TensorFlow version 2.4. 

The simplest way to initially see the content of the jupyter notebook file Assignment 0.ipynb is to use Google Colab in the cloud: (i) Use your UNI@columbia.edu account to log into Colab (https://colab.research.google.com/notebooks/intro.ipynb); (ii) Upload Assignment 0.ipynb, explore and run the file. 

For students who are formally registered into this class at the end of the add/drop period, the assignment requires that students complete the tasks from this Jupyter Notebook while running it on the Google Cloud (GCP) custom image (not Colab, Colab is only a temporary execution method).

Detailed instructions on how to submit this assignment/homework will be posted after the add/drop period.

## Welcome to ECBM E4040 Neural Networks & Deep Learning 

This course teaches theory, concepts, modeling and programming techniques. The assignments are focused on practical coding for creating, testing and running deep learning models.

The __Assignment 0__ introduces our programming environment and tools, and basic TensorFlow operations.

The assignment consists of the following components:
* Programming environment setup - Google Compute Engine/local machine, Python, TensorFlow.
* Using Jupyter Notebook
* TensorFlow basics
* A demo of a program written in TensorFlow

<p style='color:red'>Cells marked with <strong>'TODO'</strong> need to be completed by students, as a part of the assignment.</p>

Please consult TAs or post your problems/issues on Ed Discucssion.

## Part 1 - Setting up the Programming Environment

For this course, we use __Python__ as the programming language, and [__TensorFlow__](https://www.tensorflow.org) as the deep learning framework. 

Our course website (https://ecbme4040.github.io/) provides a number of tutorials:
* Local Environment Setup
* Google Compute Engine (GCE) Setup on the Google Cloud Platform (GCP)
* Python Tutorial
* TensorFlow Tutorial
* Linux Tutorial
* Git Commands
* Google Colab

<p style='color:red'><strong>TODO:</strong></p>

This list shows the big picture for what students need to do to complete the assignment. Later cells in this Jupyter notebook describe the details of the operations that need to be executed as TODO items.

* Create an account on Github, and familiarize yourself both with git operations and with Github 

* Execute Assignment0.ipynb in Colab: Fetch the Assignment0.ipynb file (from Github), upload it to Google Colab, and execute it inside the Colab environment. To do this, you need to understand python, and the operation of jupyter notebooks. This step is useful for a quick first execution. Keep the modified Jupyter notebook with your solutions.

* Create your own Google Cloud project and virtual machine (VM) instance in the Google Cloud Platform, by following the tutorial on Google Compute Engine (GCE) Setup. This will be the main and the required mode of operation for all future assignments. Note: working with Google Cloud requires funding - you can initially use the $300 that everyone gets from Google, after the add/drop period you will be given codes/coupons from the instructors.

* Execute (again) the Assignment0.ipynb within your VM in the Google Cloud. Save the resulting Jupyter Notebook. Take screenshots of the VM instance from the Google Cloud project dashboard. Take a screenshot of the Jupyter notebook when launched from google cloud. The screenshots will need to be submitted as a part of the homework to document that you have successfully launched a cloud instance. The modified Jupyter notebook which contains the populate "TODO/SOLUTIONS" portions of the code needs to be submitted.

* __(Optional)__ Set up your local laptop deep learning environment, following the tutorial on the Local Environment Setup. Since the use of Google Cloud requires funding, it is often useful to debug your code locally on a laptop, and to run it remotely in Google Cloud VM.

* __(Optional)__ Knowledge of Python, Linux and Git operations are needed for this course. Doing the tutorials is optional, depending on your prior knowledge of these topics.

* __(Optional)__ Tutorials on TensorFlow are extensive. As you progress with this course, they are an excellent complement to our class.

## Part 2 - How to use Jupyter Notebook - Basics

Jupyter Notebook is an interactive Python programming interface. Jupyter Notebook files have a postfix _.ipynb_, and each file is made up of several blocks of code which are called __cells__. Each cell can be configured as a __coding cell__ or a __Markdown text cell__. Google colab is the easiest installation-free platform to run and familiarize oneself with Jupyter Notebook operations.

Basic instructions:

* The menu bars are located on the top of a notebook.
* To execute a cell, select it, and press `ctrl+Enter`. (You may also try `shift+Enter` and `alt+Enter` to see the difference).
* To switch between code and Markdown, select a cell, and select the mode you want in the dropdown menu in the menu bar.

A full guide to Jupyter Notebook can be accessed in the _Help_ menu in the menu bar. 


In [1]:
# To test that you understand how to use a coding cell, make this cell output a string 'Hello Jupyter!'. 
# We've written the code, all you need to do is to execute it.
print('Hello Jupyter!')

Hello Jupyter!


## Part 3 - TensorFlow Basics

TensorFlow is one of the most popular deep learning frameworks. Originally created by Google, it has received a lot of community support. TensorFlow versions before v2.0 (until summer 2019) contained a number of detailed functions for construction of deep learning (neural network) models, and relied on a two-step process for model creation and execution. 
TensorFlow versions 2.0 and beyond focus on simplicity and ease of use, with updates like eager execution, intuitive Keras-based higher-level APIs, and flexible model building on any platform.

In this part, we look at some basic TensorFlow concepts and operations.

In [2]:
# This cell installs matplotlib tool, directly from Jupyter Notebook. 
# Run this cell just once after removing the '#' sign before the command.
!pip install --upgrade matplotlib
print("matplotlib installed")

You should consider upgrading via the '/home/ecbm4040/envTF24/bin/python3 -m pip install --upgrade pip' command.
matplotlib installed


In [3]:
# Activating TensorFlow in Jupyter Notebook

# Disable some warnings, to simplify the output when running the cells
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import numpy as np

# Import the TensorFlow module
import tensorflow as tf

print('TensorFlow Version=')
print(tf.__version__)

# The following modules will be used in later parts of the assignment.
# Make sure that you install the latest version of numpy and matplotlib 
#(inside your conda workspace). Alternatively, inside your virtual environment, use "conda install numpy" 
# and "conda install matplotlib" and restart the jupyter notebook. 
import numpy as np
# import input_data
%matplotlib inline
from matplotlib import pyplot as plt
import time

TensorFlow Version=
2.4.0


#### 1. Use of string constant with TensorFlow

In TensorFlow 2.0 the concept of sessions (as in versions before 2.0) has been deprecated. Now, variables are accessible instantly (as compared to after sess.run), making this flow "more pythonic in style".

In [4]:
# Example
# Define a string constant
string = tf.constant('Hello TensorFlow!')
tf.print(string)

Hello TensorFlow!


<p style='color:red'><strong>TODO:</strong></p>

Follow the example above and use TensorFlow to output the string 'YOUR_NAME:YOUR_UNI'. 

<p style='color:red'><strong>SOLUTION (enter a new cell below):</strong></p>

In [5]:
name = tf.constant('Zhihao Yi: zy2523')
tf.print(name)

Zhihao Yi: zy2523


#### 2. Basic math in TensorFlow

In [6]:
# Example

# Define 2 constant nodes. It is a good habit to name your nodes. 
# The name of the nodes will appear in the TensorBoard graph.
a = tf.constant(10, dtype=tf.float32, name='a')
b = tf.constant(20, dtype=tf.float32, name='b')

# Addition and subtraction
add = tf.add(a, b, name='add') # same as a+b
sub = tf.subtract(a, b, name='sub') # same as a-b

# There is no need for the session to run these operations (as in TensorFlow 1.*)
tf.print("a:", a)
tf.print("b:", b)
tf.print("addition:", add)
tf.print("subtraction:", sub)

a: 10
b: 20
addition: 30
subtraction: -10


<p style='color:red'><strong>TODO:</strong></p>

In [7]:
# Visit https://www.tensorflow.org/api_guides/python/math_ops 
# Find proper operations to calculate 
# a*b (multiplication), a/b (division), a^b (power) and log(a) (natural logarithm),
# and demonstrate their uses by printing their results.
# (Note: 'a' and 'b' are defined in the previous cell, you should use them directly.)

<p style='color:red'><strong>SOLUTION (enter a new cell below):</strong></p>

In [8]:
mult = tf.multiply(a, b, name='mult')
divi = tf.divide(a, b, name='divi')
power = tf.pow(a, b, name='power')
log = tf.math.log(a, name='log')
tf.print("multiplication:", mult)
tf.print("division:", divi)
tf.print("power:", power)
tf.print("log(a):", log)

multiplication: 200
division: 0.5
power: 9.99999932e+19
log(a): 2.30258512


#### 3. Constant tensor, sequences and random numbers in TensorFlow

In [9]:
# In TensorFlow, a tensor is an n-dimensional array. 
# 0-d tensor is a scalar. 1-d tensor is a vector, and so on.

# We can use TF functions to create all-zero and all-one tensors.
zero_array = tf.zeros(shape=[2,3], dtype=tf.float32, name='zero_array')
one_array = tf.ones(shape=[2,3], dtype=tf.float32, name='one_array')

# Or use a template to infer the shape.
template = tf.constant([[1,2,3],[4,5,6]], dtype=tf.float32, name='template') # Has [2,3] shape
zero_like = tf.zeros_like(template, name='zero_like')
one_like = tf.ones_like(template, name='one_like')

# Some sequence generating functions
lin_seq = tf.linspace(start=0.0, stop=5.0, num=5, name='lin_seq')
lin_range = tf.range(start=0, limit=7, delta=1, name='lin_range')

# A random number function
norm = tf.random.normal(shape=[5], mean=3, stddev=2.0)

# Printing out
tf.print('0 array:\n', zero_array)
tf.print('1 array:\n', one_array)
tf.print('0 inferred:\n', zero_like)
tf.print('1 inferred:\n', one_like)
tf.print('linear sequence:\n', lin_seq)
tf.print('range:\n', lin_range)
tf.print('Random normal:\n', norm)

0 array:
 [[0 0 0]
 [0 0 0]]
1 array:
 [[1 1 1]
 [1 1 1]]
0 inferred:
 [[0 0 0]
 [0 0 0]]
1 inferred:
 [[1 1 1]
 [1 1 1]]
linear sequence:
 [0 1.25 2.5 3.75 5]
range:
 [0 1 2 ... 4 5 6]
Random normal:
 [2.5325563 6.13428354 2.24487114 1.32184446 1.8722688]


<p style='color:red'><strong>TODO:</strong></p>

In [10]:
# 1: Generate a 3*3 matrix filled with 7s. 
# 2: Generate a sequence start from -6.0 to 7.0 (left inclusive), with step size of 1.0.
# 3: Generate another 3*3 matrix with normal distribution. Choose any mean and stddev you like.
# Hint: Visit https://www.tensorflow.org/api_guides/python/constant_op

<p style='color:red'><strong>SOLUTION (enter a new cell below):</strong></p>

In [11]:
seven_array = tf.ones(shape=[3,3], dtype=tf.float32, name='seven_array')
seven_array = seven_array * 7
lin = tf.range(start=-6, limit=7, delta=1)
nor_dis = tf.random.normal(shape=[3,3], mean=7, stddev=1)
tf.print('3x3 matrix:\n', seven_array)
tf.print('-6 to 7 linspace:\n', lin)
tf.print('normal distribution:\n', nor_dis)

3x3 matrix:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
-6 to 7 linspace:
 [-6 -5 -4 ... 4 5 6]
normal distribution:
 [[5.45485544 5.83281374 5.92778158]
 [7.04440784 8.45873928 8.11988544]
 [7.09794617 6.25012445 6.61116505]]


#### 4. Variables in TensorFlow

In [12]:
# The values of constants (previously described) can not be changed. 
# For TensorFlow variables, their values can be updated during the training of a network.

initial_value = tf.Variable([2,3], dtype=tf.float32) # You need to give an initial value to the variable.
tf.print("initial value:", initial_value)

# Several ops that can be used to change the value of a variable. 
# Note that they all become nodes in the graph.
new_value = initial_value.assign([4,5])
tf.print("assigned value:", new_value)
add = initial_value.assign_add([1,1])
tf.print("add:", add)

initial value: [2 3]
assigned value: [4 5]
add: [5 6]


<p style='color:red'><strong>TODO:</strong></p>

In [13]:
# Create a 3*3 tensor variable (the initial values don't matter).
# Assign values from 1 to 9 to it and than add 1 to each assigned value in the 3*3 tensor.
# Print out the initial values and print out the new values after the assign operation.

<p style='color:red'><strong>SOLUTION (enter a new cell below):</strong></p>

In [14]:
tensor = tf.Variable(tf.ones(shape=[3,3]), dtype=tf.float32)
tf.print('tensor matrix:\n', tensor)
assigned_tensor = tensor.assign([[1,2,3],[4,5,6],[7,8,9]])
tf.print('assigned tensor matrix:\n', assigned_tensor)
new_tensor = assigned_tensor.assign_add(tf.ones(shape=[3,3]))
tf.print('new tensor matrix:\n', new_tensor)

tensor matrix:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
assigned tensor matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
new tensor matrix:
 [[2 3 4]
 [5 6 7]
 [8 9 10]]


#### 5. Data type impact

In [15]:
# In TensorFlow, the float type of data includes float32 and float64. 
# In later assignments, 
# you should always consider float32 as the first choice for sake of efficiency, 
# even though the precision is lower than for float64.

# Here we compare the precision difference between these two types.
A32 = tf.Variable([[1,2,3], [4,5,6]], dtype=tf.float32)
B32 = (A32 + 0.2)**2
A64 = tf.Variable([[1,2,3], [4,5,6]], dtype=tf.float64)
B64 = (A64 + 0.2)**2

tf.print('float32 result: \n {}'.format(B32))
tf.print('float64 result: \n {}'.format(B64))

float32 result: 
 [[ 1.4400002  4.84      10.240001 ]
 [17.639997  27.039999  38.44     ]]
float64 result: 
 [[ 1.44  4.84 10.24]
 [17.64 27.04 38.44]]


#### 6. Distance calculation

The conventional way to measure the distance between two points in a N-dimensional space is to use the Euclidean distance, which is defined as:

Given two points $p$ and $q$, the Euclidean distance between the two is given by $d(p, q)$
$$
d(p, q) = \sqrt{\sum_{i=1}^{n}(q_i - p_i)^2}
$$

In terms of Linear Algebra, the associated norm is called the Euclidean norm. The vectorized notation for the Euclidean norm of a vector $x = (x_1, x_2, ... x_n)$ is written as:
$$
||x||_2 = \sqrt{x_1^2 + ... + x_n^2}
$$
which is valid for the n-dimensional vector space $R^n$.

Broadly speaking, the so called Euclidean norm is one of a class of Lebesgue (L-p) space norms, called L-p norms. The Euclidean norm is in fact the L-2 norm. The L-p norms are defined in similar fashion to the L-2 norm. Indeed, they are generalized from the L-2 norm as follows:

For a real number p>=1, the p-norm/L-p norm of vector x is defined as:
$$
||x||_p = (|x_1|^p + |x_2|^p + ... + |x_n|^p)^{1/p}
$$
One can see that for $p=2$, we get the L-2/Euclidean norm.

In this course, we will also encounter the L-1 norm, often called the Manhattan distance or the taxicab-metric. For a vector $x = (x_1, ... x_n)$, the L-1 norm simplifies due to $p=1$ as:
$$
||x||_1 = |x_1| + |x_2| + ... + |x_n|
$$

In keeping with this notation, the L-1 distance between two vectors $p$ and $q$ can be therefore be written as:
$$
d(p, q) = ||p - q||_1 = \sum_{i=1}^n|p_i - q_i|
$$

**NOTE**: 
The p-norms (e.g. Manhattan norm, Euclidean norm) are actually vector norms and are defined on vectors only. 

When you call the np.linalg.norm function on a matrix with ord=1 you are computing the matrix norm with order 1, which gives you the maximum of all the sums along the columns, and that's actually the correct norm for the matrix in theory. (in the case of the two matrices given below, this is 2)

Therefore, TensorFlow is abusing the definition a little bit here. So for the purposes of the below TODO task, pretend that you are asked to compute the 1-norm of each row of the difference and add all those up (which in this case is 6)

In [16]:
# Distance Calculation 
#
# Create a tensor among the following types : float32, float64, complex64, complex128
# Mentioned link details the meaning of each variable : https://www.tensorflow.org/api_docs/python/tf/norm

# create two tensors of shape 2x3.
tensor_a = tf.constant([[1,2,3], [3,2,1]], dtype=tf.float32, name='template')
tensor_b = tf.constant([[1,1,1], [1,1,1]], dtype=tf.float32, name='template')

# 1. Calculating euclidean distance or the l2 norm.

eucledian_distance = tf.norm(tensor_a - tensor_b, ord='euclidean', axis=None, keepdims=None)
tf.print("Euclidean distance:", eucledian_distance)


# 2. Calculating the Manhattan distance
manhattan_distance = tf.norm(tensor_a - tensor_b, ord=1, axis=None, keepdims=None)
tf.print("Manhattan distance:", manhattan_distance)

Euclidean distance: 3.1622777
Manhattan distance: 6


<p style='color:red'><strong>TODO:</strong></p>

In [17]:
# Create two functions using numpy which will return the euclidean distance and manhattan distance
# between the above mentioned tensors.
# Print out their outputs.

<p style='color:red'><strong>SOLUTION (enter a new cell below):</strong></p>

In [18]:
# euclidean distance
square = np.square(tensor_a - tensor_b)
eucl = np.sqrt(np.sum(square))
tf.print('Euclidean distance: ', eucl)
# manhattan distance
diff = np.absolute(tensor_a - tensor_b)
manh = np.sum(diff)
tf.print('Manhattan distance: ', manh)

Euclidean distance:  3.1622777
Manhattan distance:  6.0


We have introduced only the basic TensorFlow operations and concepts. We recommend that you visit the TensorFlow tutorial link for many more https://www.tensorflow.org/tutorials. You will need them to be able to efficiently build and execute deep learning models.

## Part 4 - TensorFlow Demos
Part 4 of this assignment consists of a demo. All you need to do is to run the demos and observe the results. This is meant to give you an idea of how TensorFlow is used.

Please run the code and look at the outputs. We do not ask you to fully understand the model at this point. However, it would be a good practice if you searched [www.tensorflow.org](https://www.tensorflow.org) to examine the functions which are used in the code. They will be really helpful when you start programming by yourself.

### Demo1: Multiclass Logistic Regression
#### Loading and preparing the MNIST dataset

In [19]:
# Multi-class Logistic Regression

from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Convert to float32.

x_train, x_test = np.array(x_train, np.float32), np.array(x_test, np.float32)

# Flatten images to 1-D vector of 784 features (28*28).
num_features = 784 
x_train, x_test = x_train.reshape([-1, num_features]), x_test.reshape([-1, num_features])

# Normalize images value from [0, 255] to [0, 1].

x_train, x_test = x_train / 255., x_test / 255. 
print("Cell executed. Move to the next cell")

Cell executed. Move to the next cell


#### Setting up hyperparameters and dataset parameters

In [20]:
# MNIST dataset parameters.

num_classes = 10 # 0 to 9 digits
num_features = 784 # 28*28

# Training parameters.

learning_rate = 0.01
training_steps = 1000
batch_size = 256
display_step = 50
print("Cell executed. Move to the next cell")

Cell executed. Move to the next cell


#### Shuffling and Batching the data

In [21]:
# Using tf.data API to shuffle and batch data.

train_data=tf.data.Dataset.from_tensor_slices((x_train,y_train))

train_data=train_data.repeat().shuffle(5000).batch(batch_size).prefetch(1)
print("Cell executed. Move to the next cell")

Cell executed. Move to the next cell


#### Initializing weights and biases

In [22]:
# Weight of shape [784, 10], the 28*28 image features, and a total number of classes.
W = tf.Variable(tf.ones([num_features, num_classes]), name="weight")

# Bias of shape [10], the total number of classes.
b = tf.Variable(tf.zeros([num_classes]), name="bias")
print("Cell executed. Move to the next cell")

Cell executed. Move to the next cell


#### Defining Logistic Regression and Cost function

In [23]:
# Logistic regression (xW + b).
def logistic_regression(x):
    # Apply softmax to normalize the logits to a probability distribution.
    return tf.nn.softmax(tf.matmul(x, W) + b)

# Cross-Entropy loss function.
def cross_entropy(y_pred, y_true):
    # Encode label to an one hot vector.
    y_true = tf.one_hot(y_true, depth=num_classes)

    # Clip prediction values to avoid log(0) error.
    y_pred = tf.clip_by_value(y_pred, 1e-9, 1.)

    # Compute cross-entropy.
    return tf.reduce_mean(-tf.reduce_sum(y_true * tf.math.log(y_pred), axis=1))

print("Cell executed. Move to the next cell")

Cell executed. Move to the next cell


#### Defining Optimizers and Accuracy Metrics

In [24]:
# Accuracy metric.
def accuracy(y_pred, y_true):
    # Predicted class is the index of the highest score in prediction vector (i.e. argmax).

    correct_prediction = tf.equal(tf.argmax(y_pred, 1), tf.cast(y_true, tf.int64))

    return tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

# Stochastic gradient descent optimizer.
optimizer = tf.optimizers.SGD(learning_rate)
print("Cell executed. Move to the next cell")

Cell executed. Move to the next cell


#### Optimization process and Updating Weights and Biases

In [25]:
# Optimization process. 

def run_optimization(x, y):
    # Wrap computation inside a GradientTape for automatic differentiation.
    with tf.GradientTape() as g:
        pred = logistic_regression(x)
        loss = cross_entropy(pred, y)
    # Compute gradients.
    gradients = g.gradient(loss, [W, b])

    # Update W and b following gradients.
    optimizer.apply_gradients(zip(gradients, [W, b]))
    
    
# printf
print("Cell executed. Move to the next cell")


Cell executed. Move to the next cell


#### Training loop

In [26]:
# Run training for the given number of steps.

print("This cell should run and show output for 1000 steps. Running ...")

for step, (batch_x, batch_y) in enumerate(train_data.take(training_steps), 1):
    # Run the optimization to update W and b values.
    run_optimization(batch_x, batch_y)
    if step % display_step == 0:
        pred = logistic_regression(batch_x)
        loss = cross_entropy(pred, batch_y)
        acc = accuracy(pred, batch_y)
        print("step: %i, loss: %f, accuracy: %f" % (step, loss, acc))
        
print("Cell executed. Move to the next cell")

This cell should run and show output for 1000 steps. Running ...
step: 50, loss: 1.860966, accuracy: 0.746094
step: 100, loss: 1.579381, accuracy: 0.757812
step: 150, loss: 1.350572, accuracy: 0.812500
step: 200, loss: 1.198314, accuracy: 0.828125
step: 250, loss: 1.003427, accuracy: 0.855469
step: 300, loss: 1.037262, accuracy: 0.812500
step: 350, loss: 0.940923, accuracy: 0.867188
step: 400, loss: 0.947955, accuracy: 0.796875
step: 450, loss: 0.824929, accuracy: 0.886719
step: 500, loss: 0.820009, accuracy: 0.812500
step: 550, loss: 0.771532, accuracy: 0.839844
step: 600, loss: 0.759377, accuracy: 0.843750
step: 650, loss: 0.689003, accuracy: 0.863281
step: 700, loss: 0.687271, accuracy: 0.851562
step: 750, loss: 0.671059, accuracy: 0.863281
step: 800, loss: 0.625561, accuracy: 0.871094
step: 850, loss: 0.625850, accuracy: 0.886719
step: 900, loss: 0.671438, accuracy: 0.820312
step: 950, loss: 0.556568, accuracy: 0.878906
step: 1000, loss: 0.672025, accuracy: 0.843750
Cell executed. 

#### Testing model accuracy using the testing data

In [27]:
# Test model on validation set.
pred = logistic_regression(x_test)
print("Test Accuracy: %f" % accuracy(pred, y_test))

Test Accuracy: 0.870200


## Part 5 - Organizing the Code for Development of Deep Learning Models
This assignment was distributed as a collection of directories and files (either through the github/bitbucket or a collection of files in a *.zip package).
The organization of directories and files is described in the corresponding README file, and illustrated below as well:
<p style='color:red'><strong>TODO Study the organization of directories and files for this assignment</strong></p>
 - In particular examine the way in which Jupyter notebook files and utility python files are distributed across directories. Students will be required to follow this (or very similar) directory structure for their assignments and projects. For every project/assignment, a similar tree structure needs to be generated and appended to the README.md file.

A typical organization of the top directory can be seen at the end of the README.md file.

### Steps to create and visualize the tree-like directory structure:
<p style='color:red'><strong>1. For Linux:</strong></p>

a. Go to the directory for which you want to create and visualize the tree structure for.

b. Type : !tree ./ >> README.md in the jupyter notebook - This will append the tree to the README.md file in the same directory.

c.  After running the above command make the following change:

- Manually enclose the whole appended text in 3 single quotes (inverted quote ```) at the top and the bottom with the same indentation. (Look at the the example mentioned below)
 
<p style='color:red'><strong>2. For Windows:</strong></p>

a. Go to the directory that you want the tree structure for.

b. Type : !tree ./ /f /a >> README.md in the jupyter notebook - This will append the tree to the README.md file in the same directory.

c.  After running the above command make below mentioned changes:

- Go to the README.md and remove the below mentioned lines 
"Folder PATH listing for volume DATA
Volume serial number is 0A8A-1CBE
D:\CA_4040\MASTER_BRANCH\E4040-2020FALL-ASSIGNMENTSALL-INSTRUCTORVERSION\ASSIGNMENT0.SOLUTION"

- Then, manually enclose the whole appended text within 3 single quotes (inverted quote ```) at the top and the bottom with the same indentation. (Look at the the example mentioned below)

d. NOTE:The two chevrons >> are used to append the output of a command to the bottom of a file (instead of one chevron which overwrites the file).


## Submission of the Assignment
The method of the submission and the naming are described in the README.md file, distributed in Github. For formal submission, additional instructions will be provided a few days before the assignment is due.

## End of the assignment

In [28]:
!sudo apt-get install tree
!tree ./ >> README.md

Reading package lists... Done
Building dependency tree       
Reading state information... Done
tree is already the newest version (1.7.0-5).
The following package was automatically installed and is no longer required:
  libnuma1
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
